<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_proceedToCheckout</name>
   <tag></tag>
   <elementGuidId>c0b985b0-7796-407f-adea-fd32f06a86f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proceedToCheckout</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
