<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_colorGroupCollapseContent</name>
   <tag></tag>
   <elementGuidId>76021e1a-2e7a-4d7d-982a-c14217218ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#collapse7</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
