<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_productTitle</name>
   <tag></tag>
   <elementGuidId>0cb3dac1-d7e4-4df1-8fd0-b9b45b416106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.product-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
