<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span.color-plastic-bags</name>
   <tag></tag>
   <elementGuidId>32d91c4e-20fa-4641-9272-886c896602c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.color-plastic-bags</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
