<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_availableColors</name>
   <tag></tag>
   <elementGuidId>b24076b3-35e3-46f4-9752-9015dd36fed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.availability</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
