<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_colorGreenCheckout</name>
   <tag></tag>
   <elementGuidId>01edf48b-5b65-4a6b-927e-27dc16101ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.color-green</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
