<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_quickOrderMenuItem</name>
   <tag></tag>
   <elementGuidId>3f167eb9-71e4-4513-8413-8d34dace5033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tactical-item[href=&quot;/quick-order/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
