<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_reorder</name>
   <tag></tag>
   <elementGuidId>e8861ba6-810b-4de6-b207-840ed76bc2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tactical-item[href=&quot;/previously-ordered/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
