<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emptyCartHolder</name>
   <tag></tag>
   <elementGuidId>65cd6d24-8295-45ea-a47a-f143671073be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cart-empty-holder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
