<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FreeClassifieds</name>
   <tag></tag>
   <elementGuidId>548ed8a9-309b-4986-b850-e9cd5d237b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;/classifieds-list/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
