<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_signUp</name>
   <tag></tag>
   <elementGuidId>b64bbec7-f2ec-4bc6-b4b8-6b45be656f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;javascript:void(0);&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
