<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_YoutubeLink</name>
   <tag></tag>
   <elementGuidId>1370db9b-5b6b-482b-8203-8ca8547b6e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;https://www.youtube.com/channel/UCuRpXEVYnsiiHTHkOAWZsww&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
