<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ChooseRegion</name>
   <tag></tag>
   <elementGuidId>86e3bea7-b243-49c5-81a5-6c3d26db6da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[data-id=&quot;region&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
