<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_regionList</name>
   <tag></tag>
   <elementGuidId>46015c08-c49c-47d6-8974-ec7cf44471b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#region</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
