<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ExpirationDateMonth</name>
   <tag></tag>
   <elementGuidId>516f9fbe-5e9e-49b6-b941-6fde4d469204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[title=&quot;Month&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
