<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SelectState</name>
   <tag></tag>
   <elementGuidId>ff6bffc3-32f1-4a8e-9bcd-87a36b9b79bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[data-id=&quot;shp1-state-select&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
