<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AddressLine</name>
   <tag></tag>
   <elementGuidId>5a09e87d-4c78-4133-bd34-598b8c6f5bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shp1-address-line</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
