<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NameOnCard</name>
   <tag></tag>
   <elementGuidId>0427b3bd-f7d1-4e3e-9a04-a27fdfc253e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
