<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SelectStateOption</name>
   <tag></tag>
   <elementGuidId>6f15718e-b2b0-4a8f-a953-31d61f390f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li//*[contains(text(),'Arizona')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
