<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_extraLargeButton</name>
   <tag></tag>
   <elementGuidId>1ca283d2-9fd6-4cf0-8e43-8ef53b455b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title*=&quot;X-Large&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
