<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_productName</name>
   <tag></tag>
   <elementGuidId>2ae066be-c73a-40a7-a3aa-f300fff81d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.product-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
