<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CartIcon</name>
   <tag></tag>
   <elementGuidId>6a0224e1-1c00-43fd-ae0b-a4eb2abcbc2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart-holder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
