<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_descriptionMore</name>
   <tag></tag>
   <elementGuidId>3815e254-61f1-4c6d-94ca-5da1194e2e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.description-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
