<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_productUnits</name>
   <tag></tag>
   <elementGuidId>3d9e36aa-8110-4ea4-982a-bbe33a7f4c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;descriptionContainer&quot;]/div[1]/div/div/div[3]/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;descriptionContainer&quot;]/div[1]/div/div/div[3]/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
