<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_skuNumber</name>
   <tag></tag>
   <elementGuidId>3ab4228b-446c-4a50-be3d-919ddcefcee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sku-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
