<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//a/*[contains(text(),'Casio')]</description>
   <name>a-CasioOption</name>
   <tag></tag>
   <elementGuidId>20585231-28c8-45c4-b796-1fdfef547965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a/*[contains(text(),'Casio')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
