<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_CasioOption</name>
   <tag></tag>
   <elementGuidId>159b756e-49e0-4223-8167-38ad40e8752f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;https://www.cleanersupply.ca/Tags-Forms/Computer-Register/?Manufacturer=Casio&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
