<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectTitle</name>
   <tag></tag>
   <elementGuidId>9f8aa70d-854b-456e-ad38-8be513265abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[title=&quot;Manufacturer&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
